using System.Collections;
using System.Collections.Generic;
using UnityEngine;

namespace gamingCloud
{
    public enum CalendarEvents
    {
        noEvent = -1,
        norouze = 0,
        Rooztabiat = 1,
        roozjomhoriEslami = 2,
        roozjahaniBehdasht = 3,
        RoozarteshEslamiIran = 4,
        veladatImamMahdi_nimeShaeban = 5,
        veladatImamHasanMojtaba = 6,
        RoozMeliKhaligFars_chehlomNorouz = 7,
        zarabtImamAli = 8,
        vafatImamAli = 9,
        shabeGhadr = 10,
        RoozJahanisalibSorkh_HelalAhmar = 11,
        eidFetr = 12,
        Roozferdowsi = 13,
        RoozAzadSaziKhoramshahr = 14,
        rehlatImamKhomeyni = 15,
        roozGhiyam15Khordad = 16,
        vafatImamSadegh = 17,
        veladatHazratMaesoomeh_roozDokhtar = 18,
        roozDezfool_roozMoghavemat = 19,
        RoozJahaniEhdaKhoon = 20,
        veladatEmamReza = 21,
        shahadatBeheshti_RoozGhoveGhazayiye = 22,
        vafatImamMohammadTaghi = 23,
        vafatImamMohammadBagher = 24,
        RoozArafeh = 25,
        EidSaeedGhorban = 26,
        veladatImamHadi = 27,
        EidSaeedGhadirKhom = 28,
        vafatImamMohammadKazem = 29,
        RoozChabDastHa = 30,
        Tasooa = 31,
        Ashora = 32,
        vafatImamSajad = 33,
        VeladatKoroush = 34,
        RoozSolhJahani = 35,
        Ghiyam17Shahrivar = 36,
        HafteDefaMoghadas = 37,
        arbaein = 38,
        rehlatPayambar_ShahadatEmamHasanMojtaba = 39,
        ShahadatEmamReza = 40,
        roozJahaniDokhtar = 41,
        ShahadatEmamHasanAskari = 42,
        miladPayambar_miladEmamJafarSadegh = 43,
        roozJavan = 44,
        roozDaneshAmooz = 45,
        veladatEmamHasanAskari = 46,
        vafatHazratMasoomeh = 47,
        roozJahaniKhoshoonatBarZanan = 48,
        roozJahaniEadz = 49,
        roozDaneshjoo = 50,
        roozParstar_veladatHazratZeinab = 51,
        shabYalda = 52,
        christmas = 53,
        miladiNewYear = 54,
        shahadatHajGhasemSoleimani = 55,
        shahadatHazratFatemeh = 56,
        roozMadar_veladatHazratFatemeh = 57,
        veladatEmamBagher = 58,
        valentine = 59,
        rooz_pedar_veladatEmamAli = 60,
        vafatHazratZeinab = 61,
        voroodEmamKhomeini = 62,
        pirooziEnghelabEslami = 63,
        dahehFajr = 64,
        shahadatEmamMoosaKazem = 65,
        mabasPeyambar = 66,
        veladatEmamHosein = 67,
        veladatHazratAbolfazl = 68,
        veladatEmamSajjad = 69,
        RoozJahaniZan = 70,
        veladatAliAkbar = 71,
        nimehShaban = 72,
        roozMeliNaft = 73,
        roozJahaniShadi = 74
    }
}